blank_issues_enabled: false
contact_links:
  - name: Security vulnerability
    url: https://github.com/0xjacq/serversguru-deploy/security/policy
    about: Please report security vulnerabilities here
  - name: Question or discussion
    url: https://github.com/0xjacq/serversguru-deploy/discussions
    about: Please use discussions for questions
